on:
  workflow_dispatch:
  create:
  release:
    types: [created]

name: build libobjc
jobs:
  build:
    name: build libobjc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get cosmos-sdk
        run: |
          cd
          mkdir -p .cosmo
          cd .cosmo
          wget https://cosmo.zip/pub/cosmocc/cosmocc-3.1.3.zip
          wget https://github.com/codehz/superconfigure/releases/download/main/aarch64-gcc.zip
          wget https://github.com/codehz/superconfigure/releases/download/main/x86_64-gcc.zip
          wget https://github.com/codehz/libobjc-for-cosmo/releases/download/main/libobjc.zip
          unzip cosmocc-3.1.3.zip
          unzip -o aarch64-gcc.zip
          unzip -o x86_64-gcc.zip
          unzip -o libobjc.zip
          rm *.zip
      - name: Fix ape
        run: |
          curl https://justine.lol/ape.elf >ape
          chmod +x ape
          sudo mv ape /usr/bin/ape
          sudo sh -c "echo ':APE:M::MZqFpD::/usr/bin/ape:' >/proc/sys/fs/binfmt_misc/register"
      - name: Run make
        run: make && tree
      - name: Export as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: libdollar
          path: |
            libdollar.a
            .aarch64/libdollar.a
            $base/*
      - name: Create zip for release
        run: |
          mkdir include
          cp -r $base include
          mkdir -p aarch64-linux-cosmo/lib/
          cp .aarch64/libdollar.a aarch64-linux-cosmo/lib/libdollar.a
          mkdir -p x86_64-linux-cosmo/lib/
          cp libdollar.a x86_64-linux-cosmo/lib/libdollar.a
          zip -r dollarbase.zip aarch64-linux-cosmo/lib/libdollar.a x86_64-linux-cosmo/lib/libdollar.a include/$base/*.h
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: "dollarbase.zip"
          overwrite: true
